### ISSUE TITLE
Performing string replacement operations in a mutating Assign policy

### ISSUE THREAD

**Issue by LarsMilland** [open-policy-agent/gatekeeper-library#216]
I am trying to find out if it possible to make an Assign policy that can target image references in Pods such that a given registry:

 - image: >-
            old-docker-registry.domain.com:5000/sample-repo/sample-app@sha256:b5a4971b67a22b87a84ec29ade5a865b1af3732a8f95f9f604b6a08f5e86ff13
            
 could be replaced with a new one:
            
 - image: >-
            new-docker-registry.domain.com:5000/sample-repo/sample-app@sha256:b5a4971b67a22b87a84ec29ade5a865b1af3732a8f95f9f604b6a08f5e86ff13     

All the examples that are using the "rego" language are non-mutating, so I am having doubt if is possible.

Could someone here confirm or deny if it would be possible to make such a mutating policy?

Also if possible could an example be created, so I could get a head start on how such a policy could look.

**Comment by maxsmythe** [comment]
It would be possible to do this with external data:

https://open-policy-agent.github.io/gatekeeper/website/docs/externaldata#external-data-for-gatekeeper-mutating-webhook

At that point, you'd be writing a webhook anyway, so hopefully you'd get some other value from using Gatekeeper, such as auth, or the ability to call multiples of these mutation webhooks in parallel (which can be very helpful for timeouts).

IMO, it's definitely worth writing a special mutator for re-writing images since that's likely a common task. It'd need to be idempotent, which means treating the field as a data structure rather than a string, but that feature doesn't currently exist.
