### ISSUE TITLE
k8spoddisruptionbudget not working when pdb created after deployment

### ISSUE THREAD

**Issue by NissesSenap** [open-policy-agent/gatekeeper-library#279]
In https://github.com/open-policy-agent/gatekeeper-library/pull/247 protection against setting minAvailable in the pdb > replicas in deployment.

Sadly this don't seem to function as we want.
I have written a simple deployment and pdb to verify this.

If I apply the PDB first and the deployment after I get an error:

``` shell
➜ k apply -f pdb.yaml    
poddisruptionbudget.policy/podinfo2-pdb created

➜ k apply -f deploy.yaml
Error from server (Forbidden): error when creating "deploy.yaml": admission webhook "validation.gatekeeper.sh" denied the request: [k8spoddisruptionbudget] Deployment <podinfo2> has 1 replica(s) but PodDisruptionBudget <podinfo2-pdb> has minAvailable of 3, PodDisruptionBudget count should always be lower than replica(s), and not used when replica(s) is set to 1
```

But if I do it the other way around, it passes:
```shell
➜ k apply -f deploy.yaml
deployment.apps/podinfo2 created

➜ k apply -f pdb.yaml   
poddisruptionbudget.policy/podinfo2-pdb created
```

If I look in k8spoddisruptionbudget you will see that OPA thinks  it's an existing violation.
```shell
k get k8spoddisruptionbudget.constraints.gatekeeper.sh -o yaml

    violations:
    - enforcementAction: deny
      group: apps
      kind: Deployment
      message: Deployment <podinfo> has 1 replica(s) but PodDisruptionBudget <podinfo-pdb>
        has minAvailable of 3, PodDisruptionBudget count should always be lower than
        replica(s), and not used when replica(s) is set to 1
      name: podinfo
      namespace: lab
      version: v1
````

```.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: podinfo2-pdb
  namespace: lab
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: podinfo2
```

```deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo2
  namespace: lab
spec:
  minReadySeconds: 3
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: podinfo2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: podinfo2
    spec:
      containers:
      - command:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --level=info
        - --backend-url=http://localhost:9898/echo
        image: ghcr.io/stefanprodan/podinfo:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: podinfo2
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        - containerPort: 9797
          name: http-metrics
          protocol: TCP
        - containerPort: 9999
          name: grpc
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```

I'm running gatekeeper version 3.11.0 installed through helm using the following values:

``` 
➜ helm get values gatekeeper
mutatingWebhookCustomRules:
- apiGroups:
  - '*'
  apiVersions:
  - '*'
  operations:
  - CREATE
  - UPDATE
  resources:
  - '*'
  - pods/ephemeralcontainers
  scope: '*'
mutatingWebhookReinvocationPolicy: IfNeeded
postInstall:
  labelNamespace:
    enabled: false
validatingWebhookFailurePolicy: Fail
```

**Comment by ctrought** [comment]
Since this is a referential policy it was a design decision to avoid needing to cache all workloads which potentially could require a lot of memory depending on the size of the cluster. Instead the PDBs are cached and the violation that checks the PDB against workload is only enforced when the workload passed through the GK webhook (ie. deployment is created after PDB, or is updated after the PDB). There is some background on that choice here.

https://github.com/open-policy-agent/gatekeeper-library/pull/177#discussion_r805103931

In your scenario if you try to update the deployment again after the PDB is applied it will be rejected,

> But if I do it the other way around, it passes:
> ➜ k apply -f deploy.yaml
> deployment.apps/podinfo2 created
>
> ➜ k apply -f pdb.yaml   
> poddisruptionbudget.policy/podinfo2-pdb created
>
>  this update should fail
> ➜ k apply -f deploy.yaml

The reason why you see the violation correctly reported in the status field is because the audit will check for existing violations in the cluster, because it runs in background against the objects in the cluster. The policy is designed to allow the objects to be applied in the way you showed which is a trade off for performance/resources that can lead to under enforcement of the policy.

https://open-policy-agent.github.io/gatekeeper/website/docs/audit/#constraint-status

You could always modify the policy to cache workloads (ie. deployments, statefulsets, etc.) instead of PDBs in the gatekeeper config and tweak the constraint to check them against the PDB admitted to the webhook. I think the original PR had this design so you could likely check it and make modifications to get the behaviour you desire.

**Comment by NissesSenap** [comment]
Thanks for the great explanation. 

Apparently I'm the second person looking in to this (I really thought I looked for open issues...) https://github.com/open-policy-agent/gatekeeper-library/issues/208 so this could probably be a bit better documented in the current feature to make sure that other people don't think it's a bug.

After some internal discussions we have decided to give it a try to verify the deployment initially as well, mainly because we don't have super big clusters so we don't think this will be an issue.
